-- Vertex migration: move pgvector dimensions from 1024 -> 768.
-- IMPORTANT:
-- 1) Run during a low-traffic window.
-- 2) Existing embeddings are cleared and must be regenerated by reindexing documents.

BEGIN;

DROP INDEX IF EXISTS chunks_embedding_idx;
DROP INDEX IF EXISTS chunks_question_embedding_idx;

-- Clear existing vectors so dimension change is safe.
UPDATE chunks
SET embedding = NULL,
    question_embedding = NULL;

ALTER TABLE chunks
    ALTER COLUMN embedding TYPE vector(768),
    ALTER COLUMN question_embedding TYPE vector(768);

CREATE INDEX chunks_embedding_idx ON chunks
    USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

CREATE INDEX chunks_question_embedding_idx ON chunks
    USING ivfflat (question_embedding vector_cosine_ops) WITH (lists = 100);

COMMIT;

-- After this migration, trigger document reindexing so chunks are re-embedded at 768 dims.
